# Image Drawing/Exporting Module
# Author: Elton Kjeld Schiott
# This class generates a PNG image file representing the data contained
# in the QR code matrix.
## @mainpage Mainpage
#
##
# @file Draw.py
# @title Draw
# @author Elton Kjeld Schiott
# @date 9/11/2016
# @brief This class generates a PNG image file representing the data 
# contained in the QR code matrix.
# @details This class takes the matrix generated by the matrix module
# and creates a PNG formatted image of the QR code to be created by the
# program.
# @code
#   image = Draw.drawQRCode(absPath, qrmatrix)
# @endcode

## @brief Method to create a PNG from the generate matrix at the given
#  file location.
#  @author Elton Kjeld Schiott
#  @details Method accepts two parameters.
#  @param absPath Accepts a string indicating the desired save directory
#  @param qrmatrix Accepts a 2D array representing the QR code matrix.
#  @return Saves a PNG file to the absPath directory
def drawQRCode(absPath, qrmatrix):
	pass
